%YAML:1.0

# pre process
ds_size: 0.25
useful_corner_num: 500

# key points
plane_detection_thre: 0.01
plane_merge_normal_thre: 0.1
plane_merge_dis_thre: 0.3
voxel_size: 2
voxel_init_num: 10
proj_plane_num: 1
proj_image_resolution: 0.5
proj_image_high_inc: 0.1
proj_dis_min: 0
proj_dis_max: 5
summary_min_thre: 10
line_filter_enable: 1

# std descriptor
descriptor_near_num: 15
descriptor_min_len: 2
descriptor_max_len: 50
max_constrait_dis: 1
triangle_resolution: 0.2

# candidate search
candidate_num: 100
sub_frame_num: 10
icp_threshold: 0.4
rough_dis_threshold: 0.01