%YAML:1.0

# pre process
ds_size: 0.25
useful_corner_num: 500
stop_skip_enable: 0

# key points
plane_detection_thre: 0.01
plane_merge_normal_thre: 0.1
plane_merge_dis_thre: 0.3
voxel_size: 2
voxel_init_num: 10
proj_plane_num: 1
proj_image_resolution: 0.5
proj_image_high_inc: 0.1
proj_dis_min: 0
proj_dis_max: 5
summary_min_thre: 10
line_filter_enable: 1
touch_filter_enable: 0

# std descriptor
descriptor_near_num: 15
descriptor_min_len: 1
descriptor_max_len: 30
max_constrait_dis: 1
triangle_resolution: 0.2

# candidate search
skip_near_num: 100
candidate_num: 50
sub_frame_num: 10
icp_threshold: 0.6
similarity_threshold: 0.7
rough_dis_threshold: 0.01
normal_threshold: 0.2
dis_threshold: 0.5

# result record
is_kitti: 1

# extrinsic
T_lidar_to_vehicle: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [1,0,0,0,
        0,1,0,0,
        0,0,1,0,
        0,0,0,1]
#  data:[ 0.999789347752932, -0.020466022556991, -0.001549851755303, 0.101800000000000,
#        -0.020441260332371,  -0.999684587556968,  0.014590417303113, -0.023700000000000,
#        -0.001847970722415,  -0.014555662875716,  -0.999892353047296, -0.023700000000000,
#         0.0, 0.0, 0.0, 1]
T_lidar_to_camera: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [1,0,0,0,
        0,1,0,0,
        0,0,1,0,
        0,0,0,1]
# gt file: 0 for kitti, 1 for mulran and cu
gt_file_style: 0

#
## pre process
#ds_size: 0.5
#useful_corner_num: 30
#stop_skip_enable: 0
#
## key points
#plane_detection_thre: 0.01
#plane_merge_normal_thre: 0.1
#plane_merge_dis_thre: 0.3
#voxel_size: 2
#voxel_init_num: 10
#proj_plane_num: 1
#proj_image_resolution: 0.5
#proj_image_high_inc: 0.1
#proj_dis_min: 0
#proj_dis_max: 5
#summary_min_thre: 10
#line_filter_enable: 1
#touch_filter_enable: 0
#
## std descriptor
#descriptor_near_num: 15
#descriptor_min_len: 1
#descriptor_max_len: 30
#max_constrait_dis: 1
#triangle_resolution: 0.2
#
## candidate search
#skip_near_num: 25
#candidate_num: 5
#sub_frame_num: 20
#icp_threshold: 0.15
#ransac_Rt_thr: 4
#similarity_threshold: 0.7
#rough_dis_threshold: 0.01
#normal_threshold: 0.2
#dis_threshold: 0.5
#
## result record
#is_kitti: 1
#
## extrinsic
#T_lidar_to_vehicle: !!opencv-matrix
#  rows: 4
#  cols: 4
#  dt: d
#  data: [1,0,0,0,
#        0,1,0,0,
#        0,0,1,0,
#        0,0,0,1]
## gt file: 0 for kitti, 1 for mulran and cu
#
#gt_file_style: 1